INSERT INTO blog_post(title,content,author_id,date_posted) VALUES
('Review of gtx','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',4,'2022-06-10'),
('Product review of xyz','love it, a great upgrade from the original.  Ive had mine for a couple of years',1,'2022-06-11'),
('First review','This pillow saved my back. I love the look and feel of this pillow.',4,'2022-06-12'),
('Bad customer service','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-13'),
('Good experience','Missing information on how to use it, but it is a great product for the price!  I',3,'2022-06-14'),
('Messed up my order','Very nice set. Good quality. We have had the set for two months now and have not been',2,'2022-06-15'),
('Perfect','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',5,'2022-06-16'),
('They are perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',1,'2022-06-17'),
('Amazing deal','love it, a great upgrade from the original.  Ive had mine for a couple of years',4,'2022-06-18'),
('Amazing gaming computer','This pillow saved my back. I love the look and feel of this pillow.',2,'2022-06-19'),
('Amazing experience','Missing information on how to use it, but it is a great product for the price!  I',2,'2022-06-20'),
('Review of gtx','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-21'),
('Product review of xyz','Very nice set. Good quality. We have had the set for two months now and have not been',1,'2022-06-22'),
('First review','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',2,'2022-06-23'),
('Bad customer service','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',1,'2022-06-24'),
('Good experience','love it, a great upgrade from the original.  Ive had mine for a couple of years',4,'2022-06-25'),
('Messed up my order','This pillow saved my back. I love the look and feel of this pillow.',3,'2022-06-26'),
('Perfect','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-10'),
('They are perfect','Missing information on how to use it, but it is a great product for the price!  I',2,'2022-06-11'),
('Amazing deal','Very nice set. Good quality. We have had the set for two months now and have not been',1,'2022-06-12'),
('Amazing gaming computer','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',1,'2022-06-13'),
('Amazing experience','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',1,'2022-06-14'),
('Perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',4,'2022-06-15'),
('They are perfect','This pillow saved my back. I love the look and feel of this pillow.',3,'2022-06-16'),
('Perfect','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-17'),
('They are perfect','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-18'),
('Amazing deal','Very nice set. Good quality. We have had the set for two months now and have not been',2,'2022-06-19'),
('Amazing gaming computer','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',3,'2022-06-20'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',2,'2022-06-21'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',2,'2022-06-22'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',4,'2022-06-23'),
('Amazing gaming computer','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-24'),
('Perfect','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-25'),
('They are perfect','Very nice set. Good quality. We have had the set for two months now and have not been',5,'2022-06-26'),
('Amazing deal','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',2,'2022-06-10'),
('Amazing gaming computer','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',1,'2022-06-11'),
('Amazing deal','love it, a great upgrade from the original.  Ive had mine for a couple of years',2,'2022-06-12'),
('Amazing gaming computer','This pillow saved my back. I love the look and feel of this pillow.',1,'2022-06-13'),
('Amazing deal','Missing information on how to use it, but it is a great product for the price!  I',2,'2022-06-14'),
('Amazing gaming computer','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-15'),
('Amazing deal','Very nice set. Good quality. We have had the set for two months now and have not been',2,'2022-06-16'),
('Amazing gaming computer','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',5,'2022-06-17'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',4,'2022-06-18'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',3,'2022-06-19'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',1,'2022-06-20'),
('Amazing gaming computer','Missing information on how to use it, but it is a great product for the price!  I',1,'2022-06-21'),
('Perfect','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-22'),
('They are perfect','Very nice set. Good quality. We have had the set for two months now and have not been',1,'2022-06-23'),
('They are perfect','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',3,'2022-06-24'),
('Amazing deal','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',4,'2022-06-25'),
('Amazing gaming computer','love it, a great upgrade from the original.  Ive had mine for a couple of years',1,'2022-06-26'),
('Perfect','This pillow saved my back. I love the look and feel of this pillow.',1,'2022-06-10'),
('First review','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-11'),
('Bad customer service','Missing information on how to use it, but it is a great product for the price!  I',3,'2022-06-12'),
('Good experience','Very nice set. Good quality. We have had the set for two months now and have not been',3,'2022-06-13'),
('Messed up my order','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',5,'2022-06-14'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',5,'2022-06-15'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',5,'2022-06-16'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',1,'2022-06-17'),
('Amazing gaming computer','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-18'),
('Amazing experience','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-19'),
('Perfect','Very nice set. Good quality. We have had the set for two months now and have not been',4,'2022-06-20'),
('They are perfect','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',4,'2022-06-21'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',4,'2022-06-22'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',2,'2022-06-23'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',1,'2022-06-24'),
('First review','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-25'),
('Bad customer service','Missing information on how to use it, but it is a great product for the price!  I',4,'2022-06-26'),
('Good experience','Very nice set. Good quality. We have had the set for two months now and have not been',3,'2022-06-10'),
('Messed up my order','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',4,'2022-06-11'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',5,'2022-06-12'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',4,'2022-06-13'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',5,'2022-06-14'),
('Amazing gaming computer','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-15'),
('Amazing experience','Missing information on how to use it, but it is a great product for the price!  I',5,'2022-06-16'),
('Perfect','Very nice set. Good quality. We have had the set for two months now and have not been',1,'2022-06-17'),
('They are perfect','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',1,'2022-06-18'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',2,'2022-06-19'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',5,'2022-06-20'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',3,'2022-06-21'),
('First review','Missing information on how to use it, but it is a great product for the price!  I',3,'2022-06-22'),
('Bad customer service','Missing information on how to use it, but it is a great product for the price!  I',1,'2022-06-23'),
('Good experience','Very nice set. Good quality. We have had the set for two months now and have not been',3,'2022-06-24'),
('Messed up my order','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',1,'2022-06-25'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',2,'2022-06-26'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',5,'2022-06-10'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',5,'2022-06-11'),
('Amazing gaming computer','Missing information on how to use it, but it is a great product for the price!  I',3,'2022-06-12'),
('Amazing experience','Missing information on how to use it, but it is a great product for the price!  I',3,'2022-06-13'),
('Perfect','Very nice set. Good quality. We have had the set for two months now and have not been',3,'2022-06-14'),
('They are perfect','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',4,'2022-06-15'),
('Perfect','Love this!  Well made, sturdy, and very comfortable.  I love it!Very pretty',5,'2022-06-16'),
('They are perfect','love it, a great upgrade from the original.  Ive had mine for a couple of years',1,'2022-06-17'),
('Amazing deal','This pillow saved my back. I love the look and feel of this pillow.',5,'2022-06-18'),
('First review','Missing information on how to use it, but it is a great product for the price!  I',2,'2022-06-19'),
('Bad customer service','Missing information on how to use it, but it is a great product for the price!  I',3,'2022-06-20'),
('Good experience','Very nice set. Good quality. We have had the set for two months now and have not been',5,'2022-06-21'),
('Messed up my order','I WANTED DIFFERENT FLAVORS BUT THEY ARE NOT.',2,'2022-06-22');
